import Event from "../types/event";

const events: Event[] = [
  {
    name: "Event Name 1",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "College 1",
    organizerType: "College",
    socialMedia: "collegeOF",
    date: "30/10/2022",
    time: "16:30",
    ticketValue: 10,
    id:11,
    local: "Local Name",
    street: "Street Pastor Jonathas",
    neighborhood: "Neighborhood 1",
    city: "city 1",
    stNumber: 10
  },
  {
    name: "Event Name 2",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "College 2",
    organizerType: "College",
    socialMedia: "collegeOF",
    date: "31/10/2022",
    time: "16:30",
    ticketValue: 30,
    id: 1,
    local: "Local Name",
    street: "Street Andre Matheus",
    neighborhood: "Neighborhood 2",
    city: "city 1",
    stNumber: 12
  },
  {
    name: "Event Name 3",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "Orange",
    organizerType: "Company",
    socialMedia: "orange.tech",
    date: "02/11/2022",
    time: "08:30",
    ticketValue: 100,
    id: 2,
    local: "Very Exclusive Local",
    street: "Money St",
    neighborhood: "Neighborhood 5",
    city: "city 2",
    stNumber: 289
  },
  {
    name: "Event Name 4",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "Google",
    organizerType: "Company",
    socialMedia: "google",
    date: "10/12/2022",
    time: "10:00",
    ticketValue: 20,
    id: 3,
    local: "Google HQ",
    street: "Street google",
    neighborhood: "Neighborhood 3",
    city: "City",
    stNumber: 1200
  },
  {
    name: "Event Name 5",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "UCLA",
    organizerType: "College",
    socialMedia: "ucla",
    date: "01/01/2023",
    time: "09:30",
    ticketValue: 40,
    id: 4,
    local: "UCLA",
    street: "college st",
    neighborhood: "collefe",
    city: "city 1",
    stNumber: 115
  },
  {
    name: "Event Name 6",
    img: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    description: "Lorem ipsum dolor sit amet. Non quia inventore cum consequuntur mollitia et autem dolores. Nam dolorem vero vel suscipit dolorem aut amet quas et sint dignissimos id iure sint aut explicabo voluptas qui nostrum fugit. Ea harum veritatis ut architecto reprehenderit et fuga molestiae ut rerum autem.",
    organizer: "UFPB",
    organizerType: "College",
    socialMedia: "ufpboficial",
    date: "30/10/2022",
    time: "16:30",
    ticketValue: 65,
    id: 5,
    local: "UFPB",
    street: "Street college",
    neighborhood: "White Castle",
    city: "JP",
    stNumber: 400
  }
];

export default events;